// Generated by `supabase gen types typescript`. Do not edit by hand; regenerate after every migration.
// (Initial version written to match migrations 0001–0005 before the first `db push`.)

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      audio_assets: {
        Row: {
          german_text: string;
          id: string;
          ipa: string | null;
          lesson_id: string;
          storage_path: string;
          translation: string | null;
        };
        Insert: {
          german_text: string;
          id?: string;
          ipa?: string | null;
          lesson_id: string;
          storage_path: string;
          translation?: string | null;
        };
        Update: {
          german_text?: string;
          id?: string;
          ipa?: string | null;
          lesson_id?: string;
          storage_path?: string;
          translation?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'audio_assets_lesson_id_fkey';
            columns: ['lesson_id'];
            isOneToOne: false;
            referencedRelation: 'lessons';
            referencedColumns: ['id'];
          },
        ];
      };
      exercises: {
        Row: {
          guiding_points: string[];
          id: string;
          lesson_id: string;
          max_words: number | null;
          min_words: number | null;
          prompt: string;
          recipient: string | null;
          task_type: Database['public']['Enums']['writing_task_type'];
        };
        Insert: {
          guiding_points?: string[];
          id?: string;
          lesson_id: string;
          max_words?: number | null;
          min_words?: number | null;
          prompt: string;
          recipient?: string | null;
          task_type?: Database['public']['Enums']['writing_task_type'];
        };
        Update: {
          guiding_points?: string[];
          id?: string;
          lesson_id?: string;
          max_words?: number | null;
          min_words?: number | null;
          prompt?: string;
          recipient?: string | null;
          task_type?: Database['public']['Enums']['writing_task_type'];
        };
        Relationships: [
          {
            foreignKeyName: 'exercises_lesson_id_fkey';
            columns: ['lesson_id'];
            isOneToOne: false;
            referencedRelation: 'lessons';
            referencedColumns: ['id'];
          },
        ];
      };
      feedback: {
        Row: {
          comment: string;
          created_at: string;
          id: string;
          score: number | null;
          submission_id: string;
          teacher_id: string;
        };
        Insert: {
          comment: string;
          created_at?: string;
          id?: string;
          score?: number | null;
          submission_id: string;
          teacher_id: string;
        };
        Update: {
          comment?: string;
          created_at?: string;
          id?: string;
          score?: number | null;
          submission_id?: string;
          teacher_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'feedback_submission_id_fkey';
            columns: ['submission_id'];
            isOneToOne: true;
            referencedRelation: 'writing_submissions';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'feedback_teacher_id_fkey';
            columns: ['teacher_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      lessons: {
        Row: {
          content_md: string;
          id: string;
          is_published: boolean;
          position: number;
          title: string;
          unit_id: string;
        };
        Insert: {
          content_md?: string;
          id?: string;
          is_published?: boolean;
          position: number;
          title: string;
          unit_id: string;
        };
        Update: {
          content_md?: string;
          id?: string;
          is_published?: boolean;
          position?: number;
          title?: string;
          unit_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'lessons_unit_id_fkey';
            columns: ['unit_id'];
            isOneToOne: false;
            referencedRelation: 'units';
            referencedColumns: ['id'];
          },
        ];
      };
      profiles: {
        Row: {
          created_at: string;
          display_name: string;
          email: string | null;
          id: string;
          role: Database['public']['Enums']['app_role'];
        };
        Insert: {
          created_at?: string;
          display_name: string;
          email?: string | null;
          id: string;
          role?: Database['public']['Enums']['app_role'];
        };
        Update: {
          created_at?: string;
          display_name?: string;
          email?: string | null;
          id?: string;
          role?: Database['public']['Enums']['app_role'];
        };
        Relationships: [];
      };
      units: {
        Row: {
          id: string;
          level: Database['public']['Enums']['cefr_level'];
          position: number;
          title: string;
        };
        Insert: {
          id?: string;
          level: Database['public']['Enums']['cefr_level'];
          position: number;
          title: string;
        };
        Update: {
          id?: string;
          level?: Database['public']['Enums']['cefr_level'];
          position?: number;
          title?: string;
        };
        Relationships: [];
      };
      useful_phrases: {
        Row: {
          category: string;
          id: string;
          position: number;
          task_type: Database['public']['Enums']['writing_task_type'];
          text: string;
        };
        Insert: {
          category: string;
          id?: string;
          position: number;
          task_type: Database['public']['Enums']['writing_task_type'];
          text: string;
        };
        Update: {
          category?: string;
          id?: string;
          position?: number;
          task_type?: Database['public']['Enums']['writing_task_type'];
          text?: string;
        };
        Relationships: [];
      };
      writing_drafts: {
        Row: {
          content: string;
          exercise_id: string;
          id: string;
          student_id: string;
          updated_at: string;
        };
        Insert: {
          content: string;
          exercise_id: string;
          id?: string;
          student_id: string;
          updated_at?: string;
        };
        Update: {
          content?: string;
          exercise_id?: string;
          id?: string;
          student_id?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'writing_drafts_exercise_id_fkey';
            columns: ['exercise_id'];
            isOneToOne: false;
            referencedRelation: 'exercises';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'writing_drafts_student_id_fkey';
            columns: ['student_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      writing_submissions: {
        Row: {
          attempt_number: number;
          content: string;
          created_at: string;
          duration_seconds: number | null;
          exercise_id: string;
          guiding_points_checked: number | null;
          id: string;
          student_id: string;
        };
        Insert: {
          attempt_number: number;
          content: string;
          created_at?: string;
          duration_seconds?: number | null;
          exercise_id: string;
          guiding_points_checked?: number | null;
          id?: string;
          student_id: string;
        };
        Update: {
          attempt_number?: number;
          content?: string;
          created_at?: string;
          duration_seconds?: number | null;
          exercise_id?: string;
          guiding_points_checked?: number | null;
          id?: string;
          student_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'writing_submissions_exercise_id_fkey';
            columns: ['exercise_id'];
            isOneToOne: false;
            referencedRelation: 'exercises';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'writing_submissions_student_id_fkey';
            columns: ['student_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      app_current_role: {
        Args: never;
        Returns: Database['public']['Enums']['app_role'];
      };
    };
    Enums: {
      app_role: 'student' | 'teacher' | 'admin';
      cefr_level: 'A1' | 'A2' | 'B1' | 'B2';
      writing_task_type: 'forum_post' | 'formal_email';
    };
    CompositeTypes: { [_ in never]: never };
  };
};
