-- Goethe-Zertifikat B2 Sprechen: initial topics for Teil 1 (Vortrag) and Teil 2 (Diskussion), for the teacher to
-- review and extend. Kept as a migration so the hosted project receives it via `supabase db push`.
-- IDs are deterministic (md5 of a stable key) so the migration is idempotent.

insert into public.speaking_topics (id, level, task_type, position, title, prompt, guiding_points, is_published) values
  (md5('zz:speaking:b2:teil1:1')::uuid, 'B2', 'presentation', 1, 'Wohnen im Alter', 'Wie sollten ältere Menschen wohnen?', array['Beschreiben Sie verschiedene Wohnformen für ältere Menschen (z. B. allein, bei der Familie, im Seniorenheim).', 'Erklären Sie eine dieser Wohnformen genauer.', 'Nennen Sie Vor- und Nachteile dieser Wohnform und bewerten Sie sie.', 'Beschreiben Sie die Situation in Ihrem Heimatland und äußern Sie Ihre Meinung.']::text[], true),
  (md5('zz:speaking:b2:teil1:2')::uuid, 'B2', 'presentation', 2, 'Homeoffice', 'Arbeiten von zu Hause – ein Modell für alle?', array['Beschreiben Sie verschiedene Arbeitsmodelle (z. B. Büro, Homeoffice, hybrides Arbeiten).', 'Erklären Sie ein Modell genauer.', 'Nennen Sie Vor- und Nachteile dieses Modells und bewerten Sie sie.', 'Beschreiben Sie die Situation in Ihrem Heimatland und äußern Sie Ihre Meinung.']::text[], true),
  (md5('zz:speaking:b2:teil1:3')::uuid, 'B2', 'presentation', 3, 'Freiwilliges soziales Jahr', 'Sollten junge Menschen nach der Schule ein soziales Jahr machen?', array['Beschreiben Sie verschiedene Möglichkeiten nach dem Schulabschluss (z. B. Studium, Ausbildung, soziales Jahr).', 'Erklären Sie eine dieser Möglichkeiten genauer.', 'Nennen Sie Vor- und Nachteile und bewerten Sie sie.', 'Beschreiben Sie die Situation in Ihrem Heimatland und äußern Sie Ihre Meinung.']::text[], true),
  (md5('zz:speaking:b2:teil1:4')::uuid, 'B2', 'presentation', 4, 'Online-Einkauf', 'Einkaufen im Internet oder im Geschäft?', array['Beschreiben Sie verschiedene Arten einzukaufen (z. B. Online-Shop, Supermarkt, Wochenmarkt).', 'Erklären Sie eine dieser Möglichkeiten genauer.', 'Nennen Sie Vor- und Nachteile und bewerten Sie sie.', 'Beschreiben Sie die Situation in Ihrem Heimatland und äußern Sie Ihre Meinung.']::text[], true),
  (md5('zz:speaking:b2:teil1:5')::uuid, 'B2', 'presentation', 5, 'Lernen mit digitalen Medien', 'Wie lernt man am besten eine Fremdsprache?', array['Beschreiben Sie verschiedene Lernmöglichkeiten (z. B. Kurs, App, Sprachreise, Tandem).', 'Erklären Sie eine dieser Möglichkeiten genauer.', 'Nennen Sie Vor- und Nachteile und bewerten Sie sie.', 'Beschreiben Sie die Situation in Ihrem Heimatland und äußern Sie Ihre Meinung.']::text[], true),
  (md5('zz:speaking:b2:teil1:6')::uuid, 'B2', 'presentation', 6, 'Ehrenamt', 'Sollte man sich in seiner Freizeit ehrenamtlich engagieren?', array['Beschreiben Sie verschiedene Formen des Ehrenamts (z. B. Sportverein, Nachbarschaftshilfe, Umweltschutz).', 'Erklären Sie eine dieser Formen genauer.', 'Nennen Sie Vor- und Nachteile und bewerten Sie sie.', 'Beschreiben Sie die Situation in Ihrem Heimatland und äußern Sie Ihre Meinung.']::text[], true),
  (md5('zz:speaking:b2:teil1:7')::uuid, 'B2', 'presentation', 7, 'Urlaub', 'Wie verbringt man den Urlaub am besten?', array['Beschreiben Sie verschiedene Urlaubsformen (z. B. Pauschalreise, Rucksackreise, Urlaub zu Hause).', 'Erklären Sie eine dieser Urlaubsformen genauer.', 'Nennen Sie Vor- und Nachteile und bewerten Sie sie.', 'Beschreiben Sie die Situation in Ihrem Heimatland und äußern Sie Ihre Meinung.']::text[], true),
  (md5('zz:speaking:b2:teil1:8')::uuid, 'B2', 'presentation', 8, 'Kinderbetreuung', 'Wer sollte kleine Kinder betreuen?', array['Beschreiben Sie verschiedene Möglichkeiten der Kinderbetreuung (z. B. Eltern, Großeltern, Kita, Tagesmutter).', 'Erklären Sie eine dieser Möglichkeiten genauer.', 'Nennen Sie Vor- und Nachteile und bewerten Sie sie.', 'Beschreiben Sie die Situation in Ihrem Heimatland und äußern Sie Ihre Meinung.']::text[], true),
  (md5('zz:speaking:b2:teil1:9')::uuid, 'B2', 'presentation', 9, 'Mobilität in der Stadt', 'Wie sollte man sich in der Stadt fortbewegen?', array['Beschreiben Sie verschiedene Verkehrsmittel in der Stadt (z. B. Auto, Fahrrad, öffentliche Verkehrsmittel, E-Scooter).', 'Erklären Sie eines dieser Verkehrsmittel genauer.', 'Nennen Sie Vor- und Nachteile und bewerten Sie sie.', 'Beschreiben Sie die Situation in Ihrem Heimatland und äußern Sie Ihre Meinung.']::text[], true),
  (md5('zz:speaking:b2:teil1:10')::uuid, 'B2', 'presentation', 10, 'Ernährung', 'Wie ernährt man sich gesund?', array['Beschreiben Sie verschiedene Ernährungsweisen (z. B. vegetarisch, vegan, Fast Food, regionale Küche).', 'Erklären Sie eine dieser Ernährungsweisen genauer.', 'Nennen Sie Vor- und Nachteile und bewerten Sie sie.', 'Beschreiben Sie die Situation in Ihrem Heimatland und äußern Sie Ihre Meinung.']::text[], true),
  (md5('zz:speaking:b2:teil2:1')::uuid, 'B2', 'discussion', 1, 'Handyverbot an Schulen', 'Sollten Handys an Schulen verboten werden?', array['Nennen Sie Argumente dafür und dagegen.', 'Äußern Sie Ihre Meinung und begründen Sie sie.', 'Reagieren Sie auf die Argumente Ihres Gesprächspartners.', 'Versuchen Sie, am Ende zu einem gemeinsamen Ergebnis zu kommen.']::text[], true),
  (md5('zz:speaking:b2:teil2:2')::uuid, 'B2', 'discussion', 2, 'Tempolimit auf Autobahnen', 'Sollte es auf allen Autobahnen ein Tempolimit geben?', array['Nennen Sie Argumente dafür und dagegen.', 'Äußern Sie Ihre Meinung und begründen Sie sie.', 'Reagieren Sie auf die Argumente Ihres Gesprächspartners.', 'Versuchen Sie, am Ende zu einem gemeinsamen Ergebnis zu kommen.']::text[], true),
  (md5('zz:speaking:b2:teil2:3')::uuid, 'B2', 'discussion', 3, 'Vier-Tage-Woche', 'Sollte die Vier-Tage-Woche für alle eingeführt werden?', array['Nennen Sie Argumente dafür und dagegen.', 'Äußern Sie Ihre Meinung und begründen Sie sie.', 'Reagieren Sie auf die Argumente Ihres Gesprächspartners.', 'Versuchen Sie, am Ende zu einem gemeinsamen Ergebnis zu kommen.']::text[], true),
  (md5('zz:speaking:b2:teil2:4')::uuid, 'B2', 'discussion', 4, 'Schuluniform', 'Sollten Schülerinnen und Schüler eine Schuluniform tragen?', array['Nennen Sie Argumente dafür und dagegen.', 'Äußern Sie Ihre Meinung und begründen Sie sie.', 'Reagieren Sie auf die Argumente Ihres Gesprächspartners.', 'Versuchen Sie, am Ende zu einem gemeinsamen Ergebnis zu kommen.']::text[], true),
  (md5('zz:speaking:b2:teil2:5')::uuid, 'B2', 'discussion', 5, 'Fleischsteuer', 'Sollte Fleisch höher besteuert werden, um das Klima zu schützen?', array['Nennen Sie Argumente dafür und dagegen.', 'Äußern Sie Ihre Meinung und begründen Sie sie.', 'Reagieren Sie auf die Argumente Ihres Gesprächspartners.', 'Versuchen Sie, am Ende zu einem gemeinsamen Ergebnis zu kommen.']::text[], true),
  (md5('zz:speaking:b2:teil2:6')::uuid, 'B2', 'discussion', 6, 'Soziale Medien für Kinder', 'Sollten soziale Medien erst ab 16 Jahren erlaubt sein?', array['Nennen Sie Argumente dafür und dagegen.', 'Äußern Sie Ihre Meinung und begründen Sie sie.', 'Reagieren Sie auf die Argumente Ihres Gesprächspartners.', 'Versuchen Sie, am Ende zu einem gemeinsamen Ergebnis zu kommen.']::text[], true),
  (md5('zz:speaking:b2:teil2:7')::uuid, 'B2', 'discussion', 7, 'Kostenloser Nahverkehr', 'Sollten Busse und Bahnen in der Stadt kostenlos sein?', array['Nennen Sie Argumente dafür und dagegen.', 'Äußern Sie Ihre Meinung und begründen Sie sie.', 'Reagieren Sie auf die Argumente Ihres Gesprächspartners.', 'Versuchen Sie, am Ende zu einem gemeinsamen Ergebnis zu kommen.']::text[], true),
  (md5('zz:speaking:b2:teil2:8')::uuid, 'B2', 'discussion', 8, 'Wahlrecht ab 16', 'Sollten Jugendliche schon mit 16 Jahren wählen dürfen?', array['Nennen Sie Argumente dafür und dagegen.', 'Äußern Sie Ihre Meinung und begründen Sie sie.', 'Reagieren Sie auf die Argumente Ihres Gesprächspartners.', 'Versuchen Sie, am Ende zu einem gemeinsamen Ergebnis zu kommen.']::text[], true),
  (md5('zz:speaking:b2:teil2:9')::uuid, 'B2', 'discussion', 9, 'Bargeld abschaffen', 'Sollte man das Bargeld abschaffen und nur noch digital bezahlen?', array['Nennen Sie Argumente dafür und dagegen.', 'Äußern Sie Ihre Meinung und begründen Sie sie.', 'Reagieren Sie auf die Argumente Ihres Gesprächspartners.', 'Versuchen Sie, am Ende zu einem gemeinsamen Ergebnis zu kommen.']::text[], true),
  (md5('zz:speaking:b2:teil2:10')::uuid, 'B2', 'discussion', 10, 'Hausaufgaben', 'Sollten Hausaufgaben abgeschafft werden?', array['Nennen Sie Argumente dafür und dagegen.', 'Äußern Sie Ihre Meinung und begründen Sie sie.', 'Reagieren Sie auf die Argumente Ihres Gesprächspartners.', 'Versuchen Sie, am Ende zu einem gemeinsamen Ergebnis zu kommen.']::text[], true)
on conflict do nothing;
